CPP="g++"
C="gcc"
C11="--std=c++11"
C14="--std=c++14"

lambda: lambda.cpp
	$(CPP) -o lambda lambda.cpp $(C11)

unique_ptr: unique_ptr.cpp
	$(CPP) -o unique_ptr unique_ptr.cpp $(C11)

3np1: 3np1.cpp
	$(CPP) -o 3np1 3np1.cpp

hello_c: hello.c
	$(CPP) -o hello_c hello.c

eof: eof.c
	$(C) -o eof eof.c

auto_lambda: auto_lambda.cpp
	$(CPP) -o auto_lambda auto_lambda.cpp $(C14)
